### ISSUE TITLE
[Tracking] Run BATS tests in CI

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-framework#137]
We need to run these tests automatically.

- [x] Try running ledger bats tests in the current CI
- [ ] Try running the resiliency tests in the current CI
- [ ] Refactor bats testing to use docker in GitHub CI

The first check will determine if we're able to run a basic client/server testing directly on the GitHub CI. Should be better than nothing if it works.

The second check will determine if we're able to run Docker-based testing directly on the Github CI. Again, it would be better than nothing.

Lastly, we'll need to refactor bats testing and Docker integration post-alpha.

**Comment by fmorency** [comment]
We also want to test BSD `coreutils` in automated BATS testing. We caught a couple of issues related to this matter during reviews which CI could have automatically seen.

**Comment by fmorency** [comment]
We can install the `many` CLI using `cargo install --git https://github.com/liftedinit/many-rs many-cli`.

I'm currently porting our CI to CircleCI + CodeCov. I'll update this issue afterward.

**Comment by hansl** [comment]
> what's the status of publishing the crates on crates.io?

I'm waiting for the refactor. We'll tlak about it on Monday.

**Comment by fmorency** [comment]
I tested the bats certified CircleCI orb on my pet project, and it works as expected. Let's work with it When the CI refactor is merged.

**Comment by hansl** [comment]
Felix to take another look here this week; there are some improvements using docker images too.
