### ISSUE TITLE
[tracking] Data Attribute work

### ISSUE THREAD

**Issue by hansl** [liftedinit/many-framework#225]
The following tasks needs to be done:

- [x] Specification merged (Issue: https://github.com/many-protocol/specification/issues/54, PR: https://github.com/many-protocol/specification/pull/56)
- [ ] E2E and resilience testing added
- [ ] Configuration (see Ops Configuration section)
- [ ] Synchronization with Tech Ops regarding this upgrade should be made (@jgryffindor)
- [ ] The Data endpoints can be added at any point, should return 0 or error if the block height isn't past.

# Ops Configuration
There is a migration step that happens at a block height. This block height is currently unknown, and will be specified when we actually deploy to the servers.

The migration name and blockheight should come from a configuration file that is passed by command line argument. This will be written by the Tech Ops.

Example configuration file:

```toml
[migrations.account_count_data]
issue = "https://github.com/liftedinit/many-framework/issues/190"
block_height = 123456789
```

The issue is useful for showing logs or just reference, but should be optional.

# Design example:

How to calculate all accounts ever seen:

From block 2200000..:
    1. Calculate the initial caching value (once) and update database
    2. When a transaction occurs;
        a. if /balances/<ADDRESS_IN_BYTES>/<MFX_IN_BYTES> exists; do nothing
        b. else; accountTotalCount += 1 and set /balances/<ADDRESS_IN_BYTES>/<MFX_IN_BYTES> = 0

Example API for migrations:

`storage.rs`

```rs
    struct:
        migrations: BTreeSet<String>

    commit():
    for migration in all_migrations {
        if current_height >= migration.block_start {
            if self.migrations.insert(migration.name) {
                // THIS CAN CHANGE THE DATABASE.
                // >>>> ONLY ONCE. <<<
                self.perform_initialization_of_migration();
            }
        }
    }

    log_event():
    if self.migrations.contains("data-upgrade-start") {
        for address in content.addresses() {
            if !self.balance_exists(address, MFX_SYMBOL) {
                self.set_balance(address, MFX_SYMBOL, 0);
            }
        }
    }
```

**Comment by fmorency** [comment]
This issue is blocked until the sync/async refactor is done in `many-rs` and `many-framework`.

See https://coda.io/d/_dY40cE5MbEt/Async-vs-Sync_suK89 for details about the underlying issue.

**Comment by hansl** [comment]
This is not blocked anymore. Will come back with more info on what remains here, but at least the migration documentation (liftedinit/many-framework#263).

**Comment by hansl** [comment]
Closing this as we're tracking the rest of the migration work elsewhere.
