### ISSUE TITLE
[tracking] Dev/release flow

### ISSUE THREAD

**Issue by fmorency** [liftedinit/many-framework#260]
Draft a document that includes 
- [x] how to develop new features
- [x] how to include new features in `main`/`next`
- [x] how to create feature releases/tags
- [x] how to create public releases/tags
- [x] how to address testing and documentation
- [x] how to track versions and changelog
- [x] how to handle hot fixes and backports

**Comment by fmorency** [comment]
@hansl Please take a look

https://coda.io/d/Developer-Onboarding_didrmCIcUQw/Development-and-release-cycles_suKuf#_lueUJ

**Comment by hansl** [comment]
I'm going to close this as the current system is good enough. We will keep the coda around until we have more engineers and teams to consolidate. WDYT @fmorency (you can reopen if you think it's important)?
